"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'irogcae'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

SESSION_COOKIE_SAMESITE = None
CSRF_COOKIE_SAMESITE = None

ALLOWED_HOSTS = [
    # coloque aqui o IP (sem porta) que você está usando no runserver:
    '172.28.245.157',
    '127.0.0.1',
    '172.28.234.202',
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'ics_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.csrf',
                'django.template.context_processors.request',
                'django.template.context_processors.debug',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'usuario_list'
#LOGOUT_REDIRECT_URL = 'login'

# Configurações de expiração de sessão
SESSION_COOKIE_AGE = 28800  # 8 horas
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_SAVE_EVERY_REQUEST = True

AUTHENTICATION_BACKENDS = [
    'accounts.backends.UsuarioBackend',           # primeiro tenta nosso backend
    'django.contrib.auth.backends.ModelBackend',  # depois o padrão, se necessário
]


# Caminho para a base de dados das Surveys usada na atualização da base de verificação.
DADOS_SURVEY_BASE_VERIFICAR_PATH = os.path.join(
    BASE_DIR, 'ics_app', 'data', 'survey'
)

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# diretório “raw data”
DATA_ROOT = BASE_DIR / "data"
DADOS_SURVEY_BASE_COMPLETA_PATH = DATA_ROOT / "survey_export_base_completa.xlsx"
DADOS_SURVEY_BASE_EXCLUIDOS_PATH = DATA_ROOT / "survey_export_excluidos.xlsx"
DADOS_SURVEY_BASE_VERIFICAR_PATH = DATA_ROOT / "survey_export_verificar.xlsx"
BASE_COMPLETA_INICIATIVA_PATH = DATA_ROOT / "base_completa_iniciativa.xlsx"
DADOS_PEDIDOS_AQ_PATH = DATA_ROOT / "dados_pedidos_aq.xlsx"
DADOS_PEDIDOS_ADIANTADOS_PATH = DATA_ROOT / "dados_pedidos_adiantados.xlsx"
DADOS_PEDIDOS_PAGOS_PATH = DATA_ROOT / "dados_pedidos_pagos.xlsx"
DADOS_PEDIDOS_PENDENTES_PATH = DATA_ROOT / "dados_pedidos_pendentes.xlsx"
RDA_SEM_PEDIDO_PATH = DATA_ROOT / "rda_sem_pedido_resumo.xlsx"
RDA_APROVADA_PATH = DATA_ROOT / "rda_aprovada.xlsx"
PROJETOS_INICIATIVAS_PATH = DATA_ROOT / "projetos_iniciativas.xlsx"

# static & templates
STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "ics_app" / "static"/ "ics_app"]
TEMPLATES[0]["DIRS"] = [BASE_DIR / "ics_app" / "templates"]

# caminhos das planilhas
EXCEL_PATH = {
    "Survey": "",  # se precisar
    "Projetos": str(BASE_DIR / "data" / "PROJECT MANAGEMENTS.xlsx"),
    "Pleitos":  BASE_DIR / "data" / "PROJECT MANAGEMENTS.xlsx",
}