# Generated by Django 5.2.3 on 2025-07-01 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dadosiniciativa',
            name='data',
        ),
        migrations.RemoveField(
            model_name='dadosiniciativa',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='dadosiniciativa',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='dadosiniciativa',
            name='valor',
        ),
        migrations.AddField(
            model_name='dadosiniciativa',
            name='categoria_de_classificacao_contabil_agrp_rda_po',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dadosiniciativa',
            name='centro_agrp_rda_po',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dadosiniciativa',
            name='centro_de_custo_agrp_rda_po',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dadosiniciativa',
            name='centro_de_lucro_agrp_rda_po',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dadosiniciativa',
            name='centro_me2n',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dadosiniciativa',
            name='centro_sq00',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dadosiniciativa',
            name='codfam_sq00',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dadosiniciativa',
            name='codigo_de_eliminacao_compromisso',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dadosiniciativa',
            name='codigo_de_eliminacao_me2n',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dadosiniciativa',
            name='codigo_de_imposto_me2n',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dadosiniciativa',
            name='codigo_de_liberacao_agrp_rda_po',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dadosiniciativa',
            name='codigo_debito_credito_sq01',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dadosiniciativa',
            name='comprador_sq00',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dadosiniciativa',
            name='cpgt_sq00',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dadosiniciativa',
            name='criado_por_agrp_rda_po',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dadosiniciativa',
            name='criado_por_sq01',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dadosiniciativa',
            name='ctg_de_historico_de_pedido_sq01',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dadosiniciativa',
            name='data_de_criacao_agrp_rda_po',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dadosiniciativa',
            name='data_de_lancamento_sq01',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dadosiniciativa',
            name='data_do_documento_compromisso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dadosiniciativa',
            name='data_do_documento_me2n',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dadosiniciativa',
            name='data_nf_sq01',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dadosiniciativa',
            name='definicao_do_projeto_compromisso',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dadosiniciativa',
            name='del_sq00',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dadosiniciativa',
            name='denomi_sq00',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dadosiniciativa',
            name='descricao_do_material_agrp_rda_po',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dadosiniciativa',
            name='doc_compra',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dadosiniciativa',
            name='doc_mat_sq01',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dadosiniciativa',
            name='doc_ref_sq01',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dadosiniciativa',
            name='dt_criacao_sq01',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dadosiniciativa',
            name='elemento_pep_agrp_rda_po',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dadosiniciativa',
            name='elemento_pep_compromisso',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dadosiniciativa',
            name='eli_sq00',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dadosiniciativa',
            name='emissao_sq00',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dadosiniciativa',
            name='empr_sq00',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dadosiniciativa',
            name='empr_sq01',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dadosiniciativa',
            name='empresa_agrp_rda_po',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dadosiniciativa',
            name='empresa_compromisso',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dadosiniciativa',
            name='fornec_sq00',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dadosiniciativa',
            name='fornecedor_agrp_rda_po',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dadosiniciativa',
            name='fornecedor_centro_fornecedor_me2n',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dadosiniciativa',
            name='fornecedor_compromisso',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dadosiniciativa',
            name='fornecedor_sq01',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dadosiniciativa',
            name='grupo_de_compradores_agrp_rda_po',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dadosiniciativa',
            name='grupo_de_mercadoria_agrp_rda_po',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dadosiniciativa',
            name='id_do_controller_agrp_rda_po',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dadosiniciativa',
            name='idioma_sq00',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dadosiniciativa',
            name='iniciativa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dadosiniciativa',
            name='item_de_requisicao_de_compras_agrp_rda_po',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dadosiniciativa',
            name='item_do_pedido_de_compras_agrp_rda_po',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dadosiniciativa',
            name='item_sq00',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dadosiniciativa',
            name='material_agrp_rda_po',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dadosiniciativa',
            name='material_sq00',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dadosiniciativa',
            name='mesa_sq00',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dadosiniciativa',
            name='moeda_me2n',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dadosiniciativa',
            name='moeda_sq01',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dadosiniciativa',
            name='montante_sq01',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dadosiniciativa',
            name='nome_1_sq01',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dadosiniciativa',
            name='nome_completo_sq01',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dadosiniciativa',
            name='numero_de_servico_agrp_rda_po',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dadosiniciativa',
            name='numero_doc_referencia_sq01',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dadosiniciativa',
            name='pgto_em_sq00',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dadosiniciativa',
            name='preco_liq_sq01',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dadosiniciativa',
            name='qtd_pedido_sq01',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dadosiniciativa',
            name='quantidade_sq01',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dadosiniciativa',
            name='razsoc_sq00',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dadosiniciativa',
            name='requisicao_de_compras_agrp_rda_po',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dadosiniciativa',
            name='status_agrp_rda_po',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dadosiniciativa',
            name='tipo_de_operacao_sq01',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dadosiniciativa',
            name='tipo_do_documento_de_compras_agrp_rda_po',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dadosiniciativa',
            name='tipo_documento_referencia_compromisso',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dadosiniciativa',
            name='tipo_sq00',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dadosiniciativa',
            name='txtbreve_sq01',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dadosiniciativa',
            name='val_comp_em_ef_moed_int_sq01',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dadosiniciativa',
            name='valor_faturas_registrada_sq01',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dadosiniciativa',
            name='valor_liquido_pedido_me2n',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dadosiniciativa',
            name='valor_moeda_objeto_compromisso',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
