# Generated by Django 5.2.3 on 2025-07-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics_app', '0002_remove_dadosiniciativa_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RdaSemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_doc_referencia', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nº doc. de referência')),
                ('total_valor_moeda_objeto', models.FloatField(blank=True, null=True, verbose_name='Total Valor/moeda objeto')),
                ('definicao_do_projeto', models.CharField(blank=True, max_length=50, null=True, verbose_name='Definição do projeto')),
                ('elemento_pep', models.CharField(blank=True, max_length=20, null=True, verbose_name='Elemento PEP')),
                ('data_do_documento', models.DateField(blank=True, null=True, verbose_name='Data do documento')),
                ('tipo_documento_referencia', models.CharField(blank=True, max_length=10, null=True, verbose_name='Tipo documento referência')),
                ('empresa', models.CharField(blank=True, max_length=100, null=True, verbose_name='Empresa')),
            ],
        ),
    ]
