# Generated by Django 5.2.3 on 2025-07-02 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ics_app', '0003_rdasempedido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dadosiniciativa',
            options={'verbose_name': 'Dado de Iniciativa', 'verbose_name_plural': 'Dados de Iniciativas'},
        ),
        migrations.AlterModelOptions(
            name='rdasempedido',
            options={'verbose_name': 'RDA Sem Pedido', 'verbose_name_plural': 'RDAs Sem Pedido'},
        ),
        migrations.AlterModelTable(
            name='dadosiniciativa',
            table='dados_iniciativas',
        ),
        migrations.AlterModelTable(
            name='rdasempedido',
            table='rda_sem_pedido',
        ),
    ]
