# Generated by Django 5.2.3 on 2025-07-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics_app', '0004_alter_dadosiniciativa_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_gerador', models.CharField(max_length=100, unique=True, verbose_name='ID Gerador')),
                ('planta', models.CharField(blank=True, max_length=100, null=True, verbose_name='Planta')),
                ('analista', models.CharField(blank=True, max_length=100, null=True, verbose_name='Analista')),
                ('status_projeto', models.CharField(blank=True, max_length=50, null=True, verbose_name='Status Projeto')),
                ('status_sop', models.CharField(blank=True, max_length=50, null=True, verbose_name='Status SOP')),
                ('qtd_visitas_realizadas', models.IntegerField(blank=True, null=True, verbose_name='QTD Visitas Realizadas')),
                ('investimento_aprovado', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Investimento Aprovado')),
                ('lead_time_projeto', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Lead Time Projeto (Meses)')),
            ],
        ),
    ]
