# Generated by Django 5.2.3 on 2025-07-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics_app', '0005_projeto'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='aprovacao_comercial',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Aprovação Comercial'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='aprovacao_saic',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Aprovação SAIC'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='aprovacao_validacao_tecnica',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Aprovação Validação Técnica'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='data_benestare',
            field=models.DateField(blank=True, null=True, verbose_name='Data Benestare'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='data_ppap_full',
            field=models.DateField(blank=True, null=True, verbose_name='Data PPAP Full'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='fornecedor',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Fornecedor'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='gerador_id_projeto',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Gerador ID Projeto'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='iaa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='IAA'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='kick_off_projeto',
            field=models.DateField(blank=True, null=True, verbose_name='Kick Off Projeto'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='last_meeting',
            field=models.DateField(blank=True, null=True, verbose_name='Last Meeting'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='lead_time_supplier',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Lead Time Supplier (Meses)'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='modelos',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Modelos'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='next_meeting',
            field=models.DateField(blank=True, null=True, verbose_name='Next Meeting'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='origem',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Origem'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='otop',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='OTOP'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='perc_conclusao_ferramental',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='% de Conclusão do Ferramental'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='po_data',
            field=models.DateField(blank=True, null=True, verbose_name='PO (Data)'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='projeto_investimento',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Projeto Investimento'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='qtd_reunioes_realizadas',
            field=models.IntegerField(blank=True, null=True, verbose_name='QTD Reuniões Realizadas'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='qty_reunioes_previstas',
            field=models.IntegerField(blank=True, null=True, verbose_name='QTY Reuniões Previstas'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='qty_visitas_previstas',
            field=models.IntegerField(blank=True, null=True, verbose_name='QTY Visitas Previstas'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='sap',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='SAP'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='sop_executado',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='SOP Executado'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='sop_target',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='SOP Target'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='spv',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='SPV'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='tipo_de_investimento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Investimento'),
        ),
    ]
