# Generated by Django 5.2.3 on 2025-07-02 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics_app', '0006_projeto_aprovacao_comercial_projeto_aprovacao_saic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pleito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pleito', models.DateField(blank=True, null=True, verbose_name='DATA PLEITO')),
                ('origem_pleito', models.CharField(blank=True, max_length=100, null=True, verbose_name='ORIGEM PLEITO')),
                ('nro_survey', models.IntegerField(blank=True, null=True, verbose_name='Nº SURVEY')),
                ('sap_supplier', models.CharField(blank=True, max_length=100, null=True, verbose_name='SAP SUPPLIER')),
                ('fornecedor_solicitado', models.CharField(blank=True, max_length=200, null=True, verbose_name='FORNECEDOR SOLICITADO')),
                ('projeto_survey', models.CharField(blank=True, max_length=200, null=True, verbose_name='PROJETO SURVEY')),
                ('pleito_inicial', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='PLEITO INICIAL')),
                ('pleito_validado', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='PLEITO VALIDADO')),
                ('pleito_valor_final', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='PLEITO VALOR FINAL')),
                ('valor_reducao', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='VALOR DE REDUÇÃO')),
                ('cost_avoidance', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='COST AVOIDANCE')),
                ('analista_responsavel', models.CharField(blank=True, max_length=100, null=True, verbose_name='ANALISTA RESPONSÁVEL')),
                ('data_cid_enviado', models.DateField(blank=True, null=True, verbose_name='DATA CID ENVIADO')),
                ('data_cid_recebido', models.DateField(blank=True, null=True, verbose_name='DATA CID RECEBIDO')),
                ('analise_de_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='ANÁLISE DE VOLUME')),
                ('validacao_comercial', models.CharField(blank=True, max_length=100, null=True, verbose_name='VALIDAÇÃO COMERCIAL')),
                ('validacao_sqd', models.CharField(blank=True, max_length=100, null=True, verbose_name='VALIDAÇÃO SQD')),
                ('data_saic', models.DateField(blank=True, null=True, verbose_name='DATA SAIC')),
                ('responsabilidade_sorting', models.CharField(blank=True, max_length=100, null=True, verbose_name='RESPONSABILIDADE SORTING')),
                ('status_pleito', models.CharField(blank=True, max_length=100, null=True, verbose_name='STATUS PLEITO')),
                ('data_analise_final', models.DateField(blank=True, null=True, verbose_name='DATA ANÁLISE FINAL')),
                ('id_pleito', models.CharField(max_length=100, unique=True, verbose_name='ID PLEITO')),
                ('id_pleito_extendido', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID PLEITO EXTENDIDO')),
                ('orientativo', models.CharField(blank=True, max_length=100, null=True, verbose_name='ORIENTATIVO')),
            ],
        ),
    ]
