# Generated by Django 5.2.3 on 2025-07-02 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics_app', '0007_pleito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='lead_time_supplier',
            field=models.IntegerField(blank=True, null=True, verbose_name='Lead Time Supplier (Meses)'),
        ),
    ]
