# Generated by Django 5.2.3 on 2025-07-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics_app', '0008_alter_projeto_lead_time_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='RDAEditada',
            fields=[
                ('nro_doc_referencia', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Nº doc. de referência')),
                ('sap_cofor', models.CharField(blank=True, max_length=100, null=True, verbose_name='SAP/COFOR')),
                ('nome_fornecedor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Fornecedor')),
            ],
        ),
    ]
