# Generated by Django 5.2.3 on 2025-07-04 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ics_app', '0009_rdaeditada'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RDAEditada',
        ),
    ]
