# Generated by Django 5.2.3 on 2025-07-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics_app', '0010_delete_rdaeditada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.CharField(max_length=50, verbose_name='Número do Pedido')),
                ('data_emissao', models.DateField(blank=True, null=True, verbose_name='Data de Emissão')),
                ('fornecedor', models.CharField(blank=True, max_length=200, null=True, verbose_name='Fornecedor')),
                ('valor_liquido', models.FloatField(blank=True, null=True, verbose_name='Valor Líquido')),
                ('iniciativa', models.CharField(blank=True, max_length=255, null=True, verbose_name='Iniciativa')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'pedidos',
            },
        ),
    ]
