# Generated by Django 5.2.3 on 2025-07-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics_app', '0011_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='data_emissao',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='fornecedor',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='numero_pedido',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='valor_liquido',
        ),
        migrations.AddField(
            model_name='pedido',
            name='comprador',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Comprador_sq00'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cpg',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cpg_sq00'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='data_documento',
            field=models.DateField(blank=True, null=True, verbose_name='Data do documento'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='data_lancamento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de lançamento'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='definicao_projeto',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Definição do projeto'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='denominacao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Denomi_sq00'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='doc_compra',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Doc Compra'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='elemento_pep',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Elemento PEP'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='empresa_compromisso',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Empresa_Compromisso'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fornecedor_codigo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Fornec_sq00 (Código Fornecedor)'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='moeda',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Moeda_me2n'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='montante',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Montante'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='preco_liquido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Preço líq.'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='razao_social',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='RazSoc_sq00 (Razão Social)'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='requisicao_compras',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Requisição de Compras (PO)'),
        ),
    ]
