# Generated by Django 5.2.3 on 2025-07-15 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics_app', '0013_dadospedidosadiantados_dadospedidosaq_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dadospedidospagos',
            name='categoria_de_classificacao_contabil_agrp_rda_po',
        ),
        migrations.RemoveField(
            model_name='dadospedidospagos',
            name='centro_agrp_rda_po',
        ),
        migrations.RemoveField(
            model_name='dadospedidospagos',
            name='centro_de_custo_agrp_rda_po',
        ),
        migrations.RemoveField(
            model_name='dadospedidospagos',
            name='centro_de_lucro_agrp_rda_po',
        ),
        migrations.RemoveField(
            model_name='dadospedidospagos',
            name='centro_me2n',
        ),
        migrations.RemoveField(
            model_name='dadospedidospagos',
            name='centro_sq00',
        ),
        migrations.RemoveField(
            model_name='dadospedidospagos',
            name='codfam_sq00',
        ),
        migrations.RemoveField(
            model_name='dadospedidospagos',
            name='codigo_de_eliminacao_compromisso',
        ),
        migrations.RemoveField(
            model_name='dadospedidospagos',
            name='codigo_de_eliminacao_me2n',
        ),
        migrations.RemoveField(
            model_name='dadospedidospagos',
            name='codigo_de_imposto_me2n',
        ),
        migrations.RemoveField(
            model_name='dadospedidospagos',
            name='codigo_de_liberacao_agrp_rda_po',
        ),
        migrations.RemoveField(
            model_name='dadospedidospagos',
            name='codigo_debito_credito_sq01',
        ),
        migrations.RemoveField(
            model_name='dadospedidospagos',
            name='criado_por_agrp_rda_po',
        ),
        migrations.RemoveField(
            model_name='dadospedidospagos',
            name='criado_por_sq01',
        ),
        migrations.RemoveField(
            model_name='dadospedidospagos',
            name='ctg_de_historico_de_pedido_sq01',
        ),
        migrations.RemoveField(
            model_name='dadospedidospagos',
            name='data_do_documento_compromisso',
        ),
        migrations.RemoveField(
            model_name='dadospedidospagos',
            name='data_do_documento_me2n',
        ),
        migrations.RemoveField(
            model_name='dadospedidospagos',
            name='del_sq00',
        ),
        migrations.RemoveField(
            model_name='dadospedidospagos',
            name='descricao_do_material_agrp_rda_po',
        ),
        migrations.RemoveField(
            model_name='dadospedidospagos',
            name='doc_mat_sq01',
        ),
        migrations.RemoveField(
            model_name='dadospedidospagos',
            name='doc_ref_sq01',
        ),
        migrations.RemoveField(
            model_name='dadospedidospagos',
            name='dt_criacao_sq01',
        ),
        migrations.RemoveField(
            model_name='dadospedidospagos',
            name='elemento_pep_compromisso',
        ),
        migrations.RemoveField(
            model_name='dadospedidospagos',
            name='eli_sq00',
        ),
        migrations.RemoveField(
            model_name='dadospedidospagos',
            name='emissao_sq00',
        ),
        migrations.RemoveField(
            model_name='dadospedidospagos',
            name='empr_sq00',
        ),
        migrations.RemoveField(
            model_name='dadospedidospagos',
            name='empr_sq01',
        ),
        migrations.RemoveField(
            model_name='dadospedidospagos',
            name='empresa_compromisso',
        ),
        migrations.RemoveField(
            model_name='dadospedidospagos',
            name='fornec_sq00',
        ),
        migrations.RemoveField(
            model_name='dadospedidospagos',
            name='fornecedor_centro_fornecedor_me2n',
        ),
        migrations.RemoveField(
            model_name='dadospedidospagos',
            name='fornecedor_compromisso',
        ),
        migrations.RemoveField(
            model_name='dadospedidospagos',
            name='fornecedor_sq01',
        ),
        migrations.RemoveField(
            model_name='dadospedidospagos',
            name='grupo_de_compradores_agrp_rda_po',
        ),
        migrations.RemoveField(
            model_name='dadospedidospagos',
            name='grupo_de_mercadoria_agrp_rda_po',
        ),
        migrations.RemoveField(
            model_name='dadospedidospagos',
            name='id_do_controller_agrp_rda_po',
        ),
        migrations.RemoveField(
            model_name='dadospedidospagos',
            name='idioma_sq00',
        ),
        migrations.RemoveField(
            model_name='dadospedidospagos',
            name='item_de_requisicao_de_compras_agrp_rda_po',
        ),
        migrations.RemoveField(
            model_name='dadospedidospagos',
            name='item_do_pedido_de_compras_agrp_rda_po',
        ),
        migrations.RemoveField(
            model_name='dadospedidospagos',
            name='item_sq00',
        ),
        migrations.RemoveField(
            model_name='dadospedidospagos',
            name='material_agrp_rda_po',
        ),
        migrations.RemoveField(
            model_name='dadospedidospagos',
            name='material_sq00',
        ),
        migrations.RemoveField(
            model_name='dadospedidospagos',
            name='mesa_sq00',
        ),
        migrations.RemoveField(
            model_name='dadospedidospagos',
            name='moeda_sq01',
        ),
        migrations.RemoveField(
            model_name='dadospedidospagos',
            name='no_doc_referencia_sq01',
        ),
        migrations.RemoveField(
            model_name='dadospedidospagos',
            name='no_servico_agrp_rda_po',
        ),
        migrations.RemoveField(
            model_name='dadospedidospagos',
            name='nome_1_sq01',
        ),
        migrations.RemoveField(
            model_name='dadospedidospagos',
            name='pgto_em_sq00',
        ),
        migrations.RemoveField(
            model_name='dadospedidospagos',
            name='preco_liq_sq01',
        ),
        migrations.RemoveField(
            model_name='dadospedidospagos',
            name='qtd_pedido_sq01',
        ),
        migrations.RemoveField(
            model_name='dadospedidospagos',
            name='quantidade_sq01',
        ),
        migrations.RemoveField(
            model_name='dadospedidospagos',
            name='status_agrp_rda_po',
        ),
        migrations.RemoveField(
            model_name='dadospedidospagos',
            name='tipo_de_operacao_sq01',
        ),
        migrations.RemoveField(
            model_name='dadospedidospagos',
            name='tipo_do_documento_de_compras_agrp_rda_po',
        ),
        migrations.RemoveField(
            model_name='dadospedidospagos',
            name='tipo_documento_referencia_compromisso',
        ),
        migrations.RemoveField(
            model_name='dadospedidospagos',
            name='tipo_sq00',
        ),
        migrations.RemoveField(
            model_name='dadospedidospagos',
            name='txtbreve_sq01',
        ),
        migrations.RemoveField(
            model_name='dadospedidospagos',
            name='valor_faturas_registrada_sq01',
        ),
        migrations.RemoveField(
            model_name='dadospedidospagos',
            name='valor_moeda_objeto_compromisso',
        ),
        migrations.RemoveField(
            model_name='dadospedidospendentes',
            name='codigo_de_eliminacao',
        ),
        migrations.RemoveField(
            model_name='dadospedidospendentes',
            name='tipo_documento_referencia',
        ),
        migrations.RemoveField(
            model_name='dadospedidospendentes',
            name='valor_moeda_objeto',
        ),
        migrations.AlterField(
            model_name='dadospedidospagos',
            name='comprador_sq00',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Comprador'),
        ),
        migrations.AlterField(
            model_name='dadospedidospagos',
            name='cpgt_sq00',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Código Pagamento'),
        ),
        migrations.AlterField(
            model_name='dadospedidospagos',
            name='data_da_rda',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Data Emissão RDA'),
        ),
        migrations.AlterField(
            model_name='dadospedidospagos',
            name='data_de_criacao_agrp_rda_po',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Data Emissão Pedido'),
        ),
        migrations.AlterField(
            model_name='dadospedidospagos',
            name='data_de_lancamento_sq01',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Data do Pagamento'),
        ),
        migrations.AlterField(
            model_name='dadospedidospagos',
            name='data_nf_sq01',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Data emissão NF'),
        ),
        migrations.AlterField(
            model_name='dadospedidospagos',
            name='definicao_do_projeto_compromisso',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Projeto'),
        ),
        migrations.AlterField(
            model_name='dadospedidospagos',
            name='denomi_sq00',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição Pagamento'),
        ),
        migrations.AlterField(
            model_name='dadospedidospagos',
            name='doc_compra',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Pedido'),
        ),
        migrations.AlterField(
            model_name='dadospedidospagos',
            name='elemento_pep_agrp_rda_po',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Elemento PEP'),
        ),
        migrations.AlterField(
            model_name='dadospedidospagos',
            name='empresa_agrp_rda_po',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Planta'),
        ),
        migrations.AlterField(
            model_name='dadospedidospagos',
            name='fornecedor_agrp_rda_po',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fornecedor'),
        ),
        migrations.AlterField(
            model_name='dadospedidospagos',
            name='iniciativa',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Iniciativa'),
        ),
        migrations.AlterField(
            model_name='dadospedidospagos',
            name='moeda_me2n',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Rate'),
        ),
        migrations.AlterField(
            model_name='dadospedidospagos',
            name='montante_sq01',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Valor Bruto'),
        ),
        migrations.AlterField(
            model_name='dadospedidospagos',
            name='nome_completo_sq01',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='dadospedidospagos',
            name='razsoc_sq00',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Razão Social'),
        ),
        migrations.AlterField(
            model_name='dadospedidospagos',
            name='requisicao_de_compras_agrp_rda_po',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='RDA'),
        ),
        migrations.AlterField(
            model_name='dadospedidospagos',
            name='val_comp_em_ef_moed_int_sq01',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Val Comp em Ef Moed Int'),
        ),
        migrations.AlterField(
            model_name='dadospedidospagos',
            name='valor_liquido_pedido_me2n',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Valor Líquido do Pedido'),
        ),
        migrations.CreateModel(
            name='FollowupIniciativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('email1', 'E-mail 1 (dia 1)'), ('email2', 'E-mail 2 (dia ≥5)')], max_length=6)),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('rda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_actions', to='ics_app.rdasempedido')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='followups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-enviado_em'],
                'unique_together': {('rda', 'tipo', 'enviado_em')},
            },
        ),
    ]
