# Generated by Django 5.2.3 on 2025-07-16 22:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics_app', '0014_remove_dadospedidospagos_categoria_de_classificacao_contabil_agrp_rda_po_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rdasempedido',
            name='tipo_documento_referencia',
        ),
        migrations.AddField(
            model_name='projeto',
            name='data_envio_daf',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='dias_corridos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='dias_uteis',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='enviado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projeto',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='rda',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ics_app.rdasempedido'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projeto',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rdasempedido',
            name='data_do_documento',
            field=models.DateField(blank=True, null=True, verbose_name='Data emissão RDA'),
        ),
        migrations.AlterField(
            model_name='rdasempedido',
            name='empresa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Planta'),
        ),
    ]
