# Generated by Django 5.2.3 on 2025-07-16 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ics_app', '0015_remove_rdasempedido_tipo_documento_referencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='data_envio_daf',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='dias_corridos',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='dias_uteis',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='enviado_em',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='observacoes',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='rda',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='user',
        ),
    ]
