# Generated by Django 5.2.3 on 2025-07-16 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics_app', '0016_remove_projeto_data_envio_daf_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='followupiniciativa',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='followupiniciativa',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='followupiniciativa',
            name='data_envio_daf',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='followupiniciativa',
            name='dias_corridos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='followupiniciativa',
            name='dias_uteis',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='followupiniciativa',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='followupiniciativa',
            name='rda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ics_app.rdasempedido'),
        ),
        migrations.AlterField(
            model_name='followupiniciativa',
            name='tipo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='followupiniciativa',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
