# Generated by Django 5.2.3 on 2025-07-17 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics_app', '0017_alter_followupiniciativa_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followupiniciativa',
            name='rda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_actions', to='ics_app.rdasempedido'),
        ),
    ]
