# Generated by Django 5.2.3 on 2025-07-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics_app', '0018_alter_followupiniciativa_rda'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdasempedido',
            name='nome_fornecedor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Fornecedor'),
        ),
        migrations.AddField(
            model_name='rdasempedido',
            name='sap_cofor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='SAP/COFOR'),
        ),
    ]
