# Generated by Django 5.2.3 on 2025-07-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics_app', '0019_rdasempedido_nome_fornecedor_rdasempedido_sap_cofor'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdasempedido',
            name='erro_rda',
            field=models.BooleanField(blank=True, null=True, verbose_name='Erro na RDA'),
        ),
    ]
