# Generated by Django 5.2.3 on 2025-07-22 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ics_app', '0021_dadosiniciativa_data_emissao_rda_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dadosiniciativa',
            name='centro_de_custo_agrp_rda_po',
        ),
        migrations.RemoveField(
            model_name='dadosiniciativa',
            name='codigo_de_eliminacao_compromisso',
        ),
        migrations.RemoveField(
            model_name='dadosiniciativa',
            name='codigo_de_eliminacao_me2n',
        ),
    ]
