# Generated by Django 5.2.3 on 2025-07-22 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ics_app', '0022_remove_dadosiniciativa_centro_de_custo_agrp_rda_po_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DadosIniciativa',
            new_name='RdaAprovada',
        ),
        migrations.AlterModelOptions(
            name='rdaaprovada',
            options={'verbose_name': 'RDA Aprovada', 'verbose_name_plural': 'RDAs Aprovadas'},
        ),
        migrations.AlterModelTable(
            name='rdaaprovada',
            table='dados_rda_aprovada',
        ),
    ]
