# Generated by Django 5.2.3 on 2025-07-24 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics_app', '0023_rename_dadosiniciativa_rdaaprovada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetoIniciativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projetos_para_extracao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Projetos para Extração')),
                ('iniciativa', models.CharField(blank=True, max_length=255, null=True, verbose_name='Iniciativa')),
                ('orcamento', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Orçamento')),
                ('status', models.CharField(blank=True, max_length=100, null=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Projeto Iniciativa',
                'verbose_name_plural': 'Projetos Iniciativas',
                'db_table': 'projeto_iniciativa',
            },
        ),
        migrations.RemoveField(
            model_name='rdaaprovada',
            name='categoria_de_classificacao_contabil_agrp_rda_po',
        ),
        migrations.RemoveField(
            model_name='rdaaprovada',
            name='centro_me2n',
        ),
        migrations.RemoveField(
            model_name='rdaaprovada',
            name='codfam_sq00',
        ),
        migrations.RemoveField(
            model_name='rdaaprovada',
            name='codigo_de_liberacao_agrp_rda_po',
        ),
        migrations.RemoveField(
            model_name='rdaaprovada',
            name='criado_por_agrp_rda_po',
        ),
        migrations.RemoveField(
            model_name='rdaaprovada',
            name='data_do_documento_compromisso',
        ),
        migrations.RemoveField(
            model_name='rdaaprovada',
            name='del_sq00',
        ),
        migrations.RemoveField(
            model_name='rdaaprovada',
            name='descricao_do_material_agrp_rda_po',
        ),
        migrations.RemoveField(
            model_name='rdaaprovada',
            name='doc_mat_sq01',
        ),
        migrations.RemoveField(
            model_name='rdaaprovada',
            name='elemento_pep_compromisso',
        ),
        migrations.RemoveField(
            model_name='rdaaprovada',
            name='eli_sq00',
        ),
        migrations.RemoveField(
            model_name='rdaaprovada',
            name='empr_sq00',
        ),
        migrations.RemoveField(
            model_name='rdaaprovada',
            name='empresa_compromisso',
        ),
        migrations.RemoveField(
            model_name='rdaaprovada',
            name='fornecedor_centro_fornecedor_me2n',
        ),
        migrations.RemoveField(
            model_name='rdaaprovada',
            name='fornecedor_compromisso',
        ),
        migrations.RemoveField(
            model_name='rdaaprovada',
            name='fornecedor_sq01',
        ),
        migrations.RemoveField(
            model_name='rdaaprovada',
            name='grupo_de_compradores_agrp_rda_po',
        ),
        migrations.RemoveField(
            model_name='rdaaprovada',
            name='grupo_de_mercadoria_agrp_rda_po',
        ),
        migrations.RemoveField(
            model_name='rdaaprovada',
            name='id_do_controller_agrp_rda_po',
        ),
        migrations.RemoveField(
            model_name='rdaaprovada',
            name='item_de_requisicao_de_compras_agrp_rda_po',
        ),
        migrations.RemoveField(
            model_name='rdaaprovada',
            name='item_do_pedido_de_compras_agrp_rda_po',
        ),
        migrations.RemoveField(
            model_name='rdaaprovada',
            name='item_sq00',
        ),
        migrations.RemoveField(
            model_name='rdaaprovada',
            name='material_agrp_rda_po',
        ),
        migrations.RemoveField(
            model_name='rdaaprovada',
            name='material_sq00',
        ),
        migrations.RemoveField(
            model_name='rdaaprovada',
            name='mesa_sq00',
        ),
        migrations.RemoveField(
            model_name='rdaaprovada',
            name='nome_1_sq01',
        ),
        migrations.RemoveField(
            model_name='rdaaprovada',
            name='numero_de_servico_agrp_rda_po',
        ),
        migrations.RemoveField(
            model_name='rdaaprovada',
            name='numero_doc_referencia_sq01',
        ),
        migrations.RemoveField(
            model_name='rdaaprovada',
            name='pgto_em_sq00',
        ),
        migrations.RemoveField(
            model_name='rdaaprovada',
            name='status_agrp_rda_po',
        ),
        migrations.RemoveField(
            model_name='rdaaprovada',
            name='tipo_de_operacao_sq01',
        ),
        migrations.RemoveField(
            model_name='rdaaprovada',
            name='tipo_do_documento_de_compras_agrp_rda_po',
        ),
        migrations.RemoveField(
            model_name='rdaaprovada',
            name='tipo_documento_referencia_compromisso',
        ),
        migrations.RemoveField(
            model_name='rdaaprovada',
            name='txtbreve_sq01',
        ),
        migrations.RemoveField(
            model_name='rdaaprovada',
            name='valor_liquido_pedido_me2n',
        ),
        migrations.AlterField(
            model_name='rdaaprovada',
            name='empr_sq01',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rdaaprovada',
            name='fornecedor_agrp_rda_po',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
