# Generated by Django 5.2.3 on 2025-07-24 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ics_app', '0024_projetoiniciativa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pleito',
            name='id_pleito_extendido',
        ),
    ]
