# Generated by Django 5.2.3 on 2025-07-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics_app', '0025_remove_pleito_id_pleito_extendido'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetoiniciativa',
            name='ano_aprovacao',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ano Aprovação'),
        ),
        migrations.AddField(
            model_name='projetoiniciativa',
            name='comite',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='E-car'),
        ),
        migrations.AddField(
            model_name='projetoiniciativa',
            name='descricao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='projetoiniciativa',
            name='e_car',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='E-car'),
        ),
        migrations.AddField(
            model_name='projetoiniciativa',
            name='planta',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Planta'),
        ),
        migrations.AddField(
            model_name='projetoiniciativa',
            name='provisao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Provisão'),
        ),
    ]
