# Generated by Django 5.2.3 on 2025-07-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics_app', '0026_projetoiniciativa_ano_aprovacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvisaoGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_projeto', models.CharField(max_length=100, verbose_name='ID do Projeto')),
                ('projeto', models.CharField(max_length=100, verbose_name='Projeto')),
                ('iniciativa', models.CharField(max_length=100, verbose_name='Iniciativa')),
                ('descricao', models.CharField(max_length=100, verbose_name='Iniciativa')),
                ('provisao', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Provisão (R$)')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Provisao Gasto',
                'verbose_name_plural': 'Provisoes Gastos',
                'db_table': 'provisao_gasto',
            },
        ),
    ]
