# Generated by Django 5.2.3 on 2025-07-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics_app', '0027_provisaogasto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rdaaprovada',
            name='centro_sq00',
        ),
        migrations.RemoveField(
            model_name='rdaaprovada',
            name='codigo_debito_credito_sq01',
        ),
        migrations.RemoveField(
            model_name='rdaaprovada',
            name='criado_por_sq01',
        ),
        migrations.RemoveField(
            model_name='rdaaprovada',
            name='data_do_documento_me2n',
        ),
        migrations.RemoveField(
            model_name='rdaaprovada',
            name='doc_ref_sq01',
        ),
        migrations.RemoveField(
            model_name='rdaaprovada',
            name='dt_criacao_sq01',
        ),
        migrations.RemoveField(
            model_name='rdaaprovada',
            name='emissao_sq00',
        ),
        migrations.RemoveField(
            model_name='rdaaprovada',
            name='empr_sq01',
        ),
        migrations.RemoveField(
            model_name='rdaaprovada',
            name='fornecedor_agrp_rda_po',
        ),
        migrations.RemoveField(
            model_name='rdaaprovada',
            name='idioma_sq00',
        ),
        migrations.RemoveField(
            model_name='rdaaprovada',
            name='moeda_sq01',
        ),
        migrations.RemoveField(
            model_name='rdaaprovada',
            name='nome_completo_sq01',
        ),
        migrations.RemoveField(
            model_name='rdaaprovada',
            name='preco_liq_sq01',
        ),
        migrations.RemoveField(
            model_name='rdaaprovada',
            name='qtd_pedido_sq01',
        ),
        migrations.RemoveField(
            model_name='rdaaprovada',
            name='quantidade_sq01',
        ),
        migrations.RemoveField(
            model_name='rdaaprovada',
            name='tipo_sq00',
        ),
        migrations.RemoveField(
            model_name='rdaaprovada',
            name='val_comp_em_ef_moed_int_sq01',
        ),
        migrations.RemoveField(
            model_name='rdaaprovada',
            name='valor_moeda_objeto_compromisso',
        ),
        migrations.AddField(
            model_name='rdaaprovada',
            name='valor_liquido_pedido_me2n',
            field=models.FloatField(blank=True, null=True, verbose_name='Valor Emissão'),
        ),
        migrations.AlterField(
            model_name='rdaaprovada',
            name='centro_agrp_rda_po',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Centro'),
        ),
        migrations.AlterField(
            model_name='rdaaprovada',
            name='centro_de_lucro_agrp_rda_po',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Centro de Lucro'),
        ),
        migrations.AlterField(
            model_name='rdaaprovada',
            name='codigo_de_imposto_me2n',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Código Imposto'),
        ),
        migrations.AlterField(
            model_name='rdaaprovada',
            name='comprador_sq00',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Comprador'),
        ),
        migrations.AlterField(
            model_name='rdaaprovada',
            name='cpgt_sq00',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Código Pg'),
        ),
        migrations.AlterField(
            model_name='rdaaprovada',
            name='ctg_de_historico_de_pedido_sq01',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo de Pag'),
        ),
        migrations.AlterField(
            model_name='rdaaprovada',
            name='data_de_criacao_agrp_rda_po',
            field=models.DateField(blank=True, null=True, verbose_name='Emissão Pedido'),
        ),
        migrations.AlterField(
            model_name='rdaaprovada',
            name='data_de_lancamento_sq01',
            field=models.DateField(blank=True, null=True, verbose_name='Data Pag/Adiant'),
        ),
        migrations.AlterField(
            model_name='rdaaprovada',
            name='data_emissao_rda',
            field=models.DateField(blank=True, null=True, verbose_name='Emissão RDA'),
        ),
        migrations.AlterField(
            model_name='rdaaprovada',
            name='data_nf_sq01',
            field=models.DateField(blank=True, null=True, verbose_name='Data NF'),
        ),
        migrations.AlterField(
            model_name='rdaaprovada',
            name='definicao_do_projeto_compromisso',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Projeto'),
        ),
        migrations.AlterField(
            model_name='rdaaprovada',
            name='denomi_sq00',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição de Pagamento'),
        ),
        migrations.AlterField(
            model_name='rdaaprovada',
            name='doc_compra',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pedido'),
        ),
        migrations.AlterField(
            model_name='rdaaprovada',
            name='elemento_pep_agrp_rda_po',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Elemento PEP'),
        ),
        migrations.AlterField(
            model_name='rdaaprovada',
            name='empresa_agrp_rda_po',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Planta'),
        ),
        migrations.AlterField(
            model_name='rdaaprovada',
            name='fornec_sq00',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SAP'),
        ),
        migrations.AlterField(
            model_name='rdaaprovada',
            name='iniciativa',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Iniciativa'),
        ),
        migrations.AlterField(
            model_name='rdaaprovada',
            name='moeda_me2n',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Moeda'),
        ),
        migrations.AlterField(
            model_name='rdaaprovada',
            name='montante_sq01',
            field=models.FloatField(blank=True, null=True, verbose_name='Valor Adiantamento'),
        ),
        migrations.AlterField(
            model_name='rdaaprovada',
            name='razsoc_sq00',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fornecedor'),
        ),
        migrations.AlterField(
            model_name='rdaaprovada',
            name='requisicao_de_compras_agrp_rda_po',
            field=models.IntegerField(blank=True, null=True, verbose_name='RDA'),
        ),
        migrations.AlterField(
            model_name='rdaaprovada',
            name='valor_faturas_registrada_sq01',
            field=models.FloatField(blank=True, null=True, verbose_name='Valor NF'),
        ),
    ]
