# Generated by Django 5.2.3 on 2025-07-28 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics_app', '0028_remove_rdaaprovada_centro_sq00_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetoiniciativa',
            name='bdgt',
            field=models.IntegerField(blank=True, null=True, verbose_name='Budget'),
        ),
        migrations.AddField(
            model_name='projetoiniciativa',
            name='disposto_sem_imposto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Orçamento'),
        ),
        migrations.AddField(
            model_name='projetoiniciativa',
            name='valor_total_pedidos_emitidos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Orçamento'),
        ),
        migrations.AddField(
            model_name='projetoiniciativa',
            name='valor_total_pedidos_pagos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Orçamento'),
        ),
        migrations.AlterField(
            model_name='provisaogasto',
            name='descricao',
            field=models.CharField(max_length=100, verbose_name='Descrição'),
        ),
    ]
