# Generated by Django 5.2.3 on 2025-07-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics_app', '0029_projetoiniciativa_bdgt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_code', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Survey Code')),
                ('sap_code', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Sap Code')),
                ('supplier', models.CharField(max_length=100, verbose_name='Supplier')),
                ('version', models.IntegerField(blank=True, null=True, verbose_name='Version')),
                ('user_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='User Name')),
                ('date_answer', models.DateField(blank=True, null=True, verbose_name='Date Answer')),
                ('company', models.CharField(blank=True, max_length=100, null=True, verbose_name='Company')),
                ('partnumber', models.CharField(blank=True, max_length=100, null=True, verbose_name='Part Number')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Base Survey',
                'verbose_name_plural': 'Bases Surveys',
                'db_table': 'dados_survey',
            },
        ),
        migrations.AlterModelOptions(
            name='dadospedidosadiantados',
            options={'verbose_name': 'PedidoAdiantados', 'verbose_name_plural': 'PedidoAdiantados'},
        ),
        migrations.AlterField(
            model_name='projetoiniciativa',
            name='bdgt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Planta'),
        ),
        migrations.AlterField(
            model_name='projetoiniciativa',
            name='disposto_sem_imposto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Disposto S/ Imposto'),
        ),
        migrations.AlterField(
            model_name='projetoiniciativa',
            name='valor_total_pedidos_emitidos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Total Pedidos Emitidos'),
        ),
        migrations.AlterField(
            model_name='projetoiniciativa',
            name='valor_total_pedidos_pagos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Total Pedidos Pagos'),
        ),
        migrations.AlterModelTable(
            name='dadospedidosadiantados',
            table='dados_pedidos_adiantados',
        ),
        migrations.AlterModelTable(
            name='dadospedidosaq',
            table='dados_pedidos_aq',
        ),
        migrations.AlterModelTable(
            name='dadospedidospagos',
            table='dados_pedidos_pagos',
        ),
        migrations.AlterModelTable(
            name='dadospedidospendentes',
            table='dados_pedidos_pendentes',
        ),
        migrations.AlterModelTable(
            name='pedido',
            table='dados_pedidos',
        ),
    ]
