# Generated by Django 5.2.3 on 2025-07-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics_app', '0030_survey_alter_dadospedidosadiantados_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='sap_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='SAP Code'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Survey Code'),
        ),
    ]
