# Generated by Django 5.2.3 on 2025-07-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics_app', '0031_alter_survey_sap_code_alter_survey_survey_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='supplier',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Supplier'),
        ),
    ]
