# Generated by Django 5.2.3 on 2025-07-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics_app', '0032_alter_survey_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='provisaogasto',
            name='fornecedor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fornecedor'),
        ),
    ]
