# Generated by Django 5.2.3 on 2025-07-30 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics_app', '0033_provisaogasto_fornecedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='provisaogasto',
            name='sap',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='SAP'),
        ),
    ]
