# Generated by Django 5.2.3 on 2025-08-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics_app', '0034_provisaogasto_sap'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyBaseOk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_code', models.IntegerField(blank=True, null=True, verbose_name='Survey Code')),
                ('sap_code', models.IntegerField(blank=True, null=True, verbose_name='SAP Code')),
                ('supplier', models.CharField(blank=True, max_length=100, null=True, verbose_name='Supplier')),
                ('version', models.IntegerField(blank=True, null=True, verbose_name='Version')),
                ('user_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='User Name')),
                ('date_answer', models.DateField(blank=True, null=True, verbose_name='Date Answer')),
                ('company', models.CharField(blank=True, max_length=100, null=True, verbose_name='Company')),
                ('partnumber', models.CharField(blank=True, max_length=100, null=True, verbose_name='Part Number')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Base OK',
                'verbose_name_plural': 'Bases OK',
                'db_table': 'survey_base_ok',
            },
        ),
        migrations.CreateModel(
            name='SurveyBaseVerificarPleito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_code', models.IntegerField(blank=True, null=True, verbose_name='Survey Code')),
                ('sap_code', models.IntegerField(blank=True, null=True, verbose_name='SAP Code')),
                ('supplier', models.CharField(blank=True, max_length=100, null=True, verbose_name='Supplier')),
                ('version', models.IntegerField(blank=True, null=True, verbose_name='Version')),
                ('user_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='User Name')),
                ('date_answer', models.DateField(blank=True, null=True, verbose_name='Date Answer')),
                ('company', models.CharField(blank=True, max_length=100, null=True, verbose_name='Company')),
                ('partnumber', models.CharField(blank=True, max_length=100, null=True, verbose_name='Part Number')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Base Verificar Pleito',
                'verbose_name_plural': 'Bases Verificar Pleito',
                'db_table': 'survey_base_verificar_pleito',
            },
        ),
        migrations.RenameModel(
            old_name='Survey',
            new_name='SurveyBaseCompleta',
        ),
        migrations.AlterModelOptions(
            name='surveybasecompleta',
            options={'verbose_name': 'Base Completa', 'verbose_name_plural': 'Bases Completas'},
        ),
        migrations.AlterField(
            model_name='projetoiniciativa',
            name='comite',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Comitê'),
        ),
        migrations.AlterModelTable(
            name='surveybasecompleta',
            table='survey_base_completa',
        ),
    ]
