# Generated by Django 5.2.3 on 2025-08-06 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics_app', '0035_surveybaseok_surveybaseverificarpleito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveybasecompleta',
            name='annual_volume_2026',
            field=models.IntegerField(blank=True, null=True, verbose_name='Annual Volume(s) 2026'),
        ),
        migrations.AddField(
            model_name='surveybasecompleta',
            name='april',
            field=models.IntegerField(blank=True, null=True, verbose_name='April'),
        ),
        migrations.AddField(
            model_name='surveybasecompleta',
            name='august',
            field=models.IntegerField(blank=True, null=True, verbose_name='August'),
        ),
        migrations.AddField(
            model_name='surveybasecompleta',
            name='currency',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='surveybasecompleta',
            name='december',
            field=models.IntegerField(blank=True, null=True, verbose_name='December'),
        ),
        migrations.AddField(
            model_name='surveybasecompleta',
            name='february',
            field=models.IntegerField(blank=True, null=True, verbose_name='February'),
        ),
        migrations.AddField(
            model_name='surveybasecompleta',
            name='investment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Investment'),
        ),
        migrations.AddField(
            model_name='surveybasecompleta',
            name='investment_dolares',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Investment($)'),
        ),
        migrations.AddField(
            model_name='surveybasecompleta',
            name='investment_reais',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Investment Reais (R$)'),
        ),
        migrations.AddField(
            model_name='surveybasecompleta',
            name='january',
            field=models.IntegerField(blank=True, null=True, verbose_name='January'),
        ),
        migrations.AddField(
            model_name='surveybasecompleta',
            name='july',
            field=models.IntegerField(blank=True, null=True, verbose_name='July'),
        ),
        migrations.AddField(
            model_name='surveybasecompleta',
            name='june',
            field=models.IntegerField(blank=True, null=True, verbose_name='June'),
        ),
        migrations.AddField(
            model_name='surveybasecompleta',
            name='march',
            field=models.IntegerField(blank=True, null=True, verbose_name='March'),
        ),
        migrations.AddField(
            model_name='surveybasecompleta',
            name='may',
            field=models.IntegerField(blank=True, null=True, verbose_name='May'),
        ),
        migrations.AddField(
            model_name='surveybasecompleta',
            name='november',
            field=models.IntegerField(blank=True, null=True, verbose_name='November'),
        ),
        migrations.AddField(
            model_name='surveybasecompleta',
            name='october',
            field=models.IntegerField(blank=True, null=True, verbose_name='October'),
        ),
        migrations.AddField(
            model_name='surveybasecompleta',
            name='september',
            field=models.IntegerField(blank=True, null=True, verbose_name='September'),
        ),
        migrations.AddField(
            model_name='surveybasecompleta',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='surveybasecompleta',
            name='weekly_peak_pico_semanal',
            field=models.IntegerField(blank=True, null=True, verbose_name='Weekly Peak (Pico Semanal)'),
        ),
        migrations.AddField(
            model_name='surveybaseok',
            name='annual_volume_2026',
            field=models.IntegerField(blank=True, null=True, verbose_name='Annual Volume(s) 2026'),
        ),
        migrations.AddField(
            model_name='surveybaseok',
            name='april',
            field=models.IntegerField(blank=True, null=True, verbose_name='April'),
        ),
        migrations.AddField(
            model_name='surveybaseok',
            name='august',
            field=models.IntegerField(blank=True, null=True, verbose_name='August'),
        ),
        migrations.AddField(
            model_name='surveybaseok',
            name='currency',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='surveybaseok',
            name='december',
            field=models.IntegerField(blank=True, null=True, verbose_name='December'),
        ),
        migrations.AddField(
            model_name='surveybaseok',
            name='february',
            field=models.IntegerField(blank=True, null=True, verbose_name='February'),
        ),
        migrations.AddField(
            model_name='surveybaseok',
            name='investment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Investment'),
        ),
        migrations.AddField(
            model_name='surveybaseok',
            name='investment_dolares',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Investment($)'),
        ),
        migrations.AddField(
            model_name='surveybaseok',
            name='investment_reais',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Investment Reais (R$)'),
        ),
        migrations.AddField(
            model_name='surveybaseok',
            name='january',
            field=models.IntegerField(blank=True, null=True, verbose_name='January'),
        ),
        migrations.AddField(
            model_name='surveybaseok',
            name='july',
            field=models.IntegerField(blank=True, null=True, verbose_name='July'),
        ),
        migrations.AddField(
            model_name='surveybaseok',
            name='june',
            field=models.IntegerField(blank=True, null=True, verbose_name='June'),
        ),
        migrations.AddField(
            model_name='surveybaseok',
            name='march',
            field=models.IntegerField(blank=True, null=True, verbose_name='March'),
        ),
        migrations.AddField(
            model_name='surveybaseok',
            name='may',
            field=models.IntegerField(blank=True, null=True, verbose_name='May'),
        ),
        migrations.AddField(
            model_name='surveybaseok',
            name='november',
            field=models.IntegerField(blank=True, null=True, verbose_name='November'),
        ),
        migrations.AddField(
            model_name='surveybaseok',
            name='october',
            field=models.IntegerField(blank=True, null=True, verbose_name='October'),
        ),
        migrations.AddField(
            model_name='surveybaseok',
            name='september',
            field=models.IntegerField(blank=True, null=True, verbose_name='September'),
        ),
        migrations.AddField(
            model_name='surveybaseok',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='surveybaseok',
            name='weekly_peak_pico_semanal',
            field=models.IntegerField(blank=True, null=True, verbose_name='Weekly Peak (Pico Semanal)'),
        ),
        migrations.AddField(
            model_name='surveybaseverificarpleito',
            name='annual_volume_2026',
            field=models.IntegerField(blank=True, null=True, verbose_name='Annual Volume(s) 2026'),
        ),
        migrations.AddField(
            model_name='surveybaseverificarpleito',
            name='april',
            field=models.IntegerField(blank=True, null=True, verbose_name='April'),
        ),
        migrations.AddField(
            model_name='surveybaseverificarpleito',
            name='august',
            field=models.IntegerField(blank=True, null=True, verbose_name='August'),
        ),
        migrations.AddField(
            model_name='surveybaseverificarpleito',
            name='currency',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='surveybaseverificarpleito',
            name='december',
            field=models.IntegerField(blank=True, null=True, verbose_name='December'),
        ),
        migrations.AddField(
            model_name='surveybaseverificarpleito',
            name='february',
            field=models.IntegerField(blank=True, null=True, verbose_name='February'),
        ),
        migrations.AddField(
            model_name='surveybaseverificarpleito',
            name='investment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Investment'),
        ),
        migrations.AddField(
            model_name='surveybaseverificarpleito',
            name='investment_dolares',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Investment($)'),
        ),
        migrations.AddField(
            model_name='surveybaseverificarpleito',
            name='investment_reais',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Investment Reais (R$)'),
        ),
        migrations.AddField(
            model_name='surveybaseverificarpleito',
            name='january',
            field=models.IntegerField(blank=True, null=True, verbose_name='January'),
        ),
        migrations.AddField(
            model_name='surveybaseverificarpleito',
            name='july',
            field=models.IntegerField(blank=True, null=True, verbose_name='July'),
        ),
        migrations.AddField(
            model_name='surveybaseverificarpleito',
            name='june',
            field=models.IntegerField(blank=True, null=True, verbose_name='June'),
        ),
        migrations.AddField(
            model_name='surveybaseverificarpleito',
            name='march',
            field=models.IntegerField(blank=True, null=True, verbose_name='March'),
        ),
        migrations.AddField(
            model_name='surveybaseverificarpleito',
            name='may',
            field=models.IntegerField(blank=True, null=True, verbose_name='May'),
        ),
        migrations.AddField(
            model_name='surveybaseverificarpleito',
            name='november',
            field=models.IntegerField(blank=True, null=True, verbose_name='November'),
        ),
        migrations.AddField(
            model_name='surveybaseverificarpleito',
            name='october',
            field=models.IntegerField(blank=True, null=True, verbose_name='October'),
        ),
        migrations.AddField(
            model_name='surveybaseverificarpleito',
            name='september',
            field=models.IntegerField(blank=True, null=True, verbose_name='September'),
        ),
        migrations.AddField(
            model_name='surveybaseverificarpleito',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='surveybaseverificarpleito',
            name='weekly_peak_pico_semanal',
            field=models.IntegerField(blank=True, null=True, verbose_name='Weekly Peak (Pico Semanal)'),
        ),
    ]
